name: Deploy Azure Resources and Web Application to all Environments

on:
  push:
    branches:
    - master
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      home-app: ${{ steps.filter.outputs.home-app }}
      news-feed: ${{ steps.filter.outputs.news-feed }}
      shared-components: ${{ steps.filter.outputs.shared-components }}
    steps:
    # For pull requests it's not necessary to checkout the code
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          home-app:
            - 'home-app/**'
          news-feed:
            - 'news-feed/**'
          shared-components:
            - 'shared-components/**'
  deploy-shared-components-app-to-prod:
    needs: changes
    if: ${{ needs.changes.outputs.shared-components == 'true' }}
    uses: './.github/workflows/deploy-infra-and-website-to-env.yml'
    with:
      dockerContext: './shared-components'
      dockerFilePath: './shared-components/Dockerfile'
      microFrontendService: 'shared-components'
      environmentType: 'prod'
      resourceGroupName: intrinsic-rg
      dockerBaseUrl: index.docker.io
      dockerImageNameAndTag: module-federation-shared-components:latest
    secrets:
      clientId: ${{ secrets.AZURE_CLIENT_ID }}
      tenantId: ${{ secrets.AZURE_TENANT_ID }}
      subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      dockerUsername: ${{ secrets.DOCKER_USERNAME }}
      dockerPassword: ${{ secrets.DOCKER_PASSWORD }}
  deploy-news-feed-to-prod:
    needs: changes
    if: ${{ needs.changes.outputs.news-feed == 'true' }}
    uses: './.github/workflows/deploy-infra-and-website-to-env.yml'
    with:
      dockerContext: './news-feed'
      dockerFilePath: './news-feed/Dockerfile'
      microFrontendService: 'news-feed'
      environmentType: 'prod'
      resourceGroupName: intrinsic-rg
      dockerBaseUrl: index.docker.io
      dockerImageNameAndTag: module-federation-news-feed:latest
    secrets:
      clientId: ${{ secrets.AZURE_CLIENT_ID }}
      tenantId: ${{ secrets.AZURE_TENANT_ID }}
      subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      dockerUsername: ${{ secrets.DOCKER_USERNAME }}
      dockerPassword: ${{ secrets.DOCKER_PASSWORD }}
  deploy-home-app-to-prod:
    needs: changes
    if: ${{ needs.changes.outputs.home-app == 'true' }}
    uses: './.github/workflows/deploy-infra-and-website-to-env.yml'
    with:
      dockerContext: './home-app'
      dockerFilePath: './home-app/Dockerfile'
      microFrontendService: 'home-app'
      environmentType: 'prod'
      resourceGroupName: intrinsic-rg
      dockerBaseUrl: index.docker.io
      dockerImageNameAndTag: module-federation-home-app:latest
    secrets:
      clientId: ${{ secrets.AZURE_CLIENT_ID }}
      tenantId: ${{ secrets.AZURE_TENANT_ID }}
      subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      dockerUsername: ${{ secrets.DOCKER_USERNAME }}
      dockerPassword: ${{ secrets.DOCKER_PASSWORD }}
