name: Deploy Azure Resources and Web Application to all Environments

on:
  push:
    branches:
    - master
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-shared-components-app-to-prod:
    uses: './.github/workflows/deploy-infra-and-website-to-env.yml'
    with:
      dockerContext: './shared-components'
      dockerFilePath: './shared-components/Dockerfile'
      microFrontendService: 'shared-components'
      environmentType: 'prod'
      resourceGroupName: intrinsic-rg
      dockerBaseUrl: index.docker.io
      dockerImageNameAndTag: module-federation-shared-components:latest
    secrets:
      clientId: ${{ secrets.AZURE_CLIENT_ID }}
      tenantId: ${{ secrets.AZURE_TENANT_ID }}
      subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      dockerUsername: ${{ secrets.DOCKER_USERNAME }}
      dockerPassword: ${{ secrets.DOCKER_PASSWORD }}
  deploy-news-feed-to-prod:
    uses: './.github/workflows/deploy-infra-and-website-to-env.yml'
    needs: [deploy-shared-components-app-to-prod]
    with:
      dockerContext: './news-feed'
      dockerFilePath: './news-feed/Dockerfile'
      microFrontendService: 'news-feed'
      environmentType: 'prod'
      resourceGroupName: intrinsic-rg
      dockerBaseUrl: index.docker.io
      dockerImageNameAndTag: module-federation-news-feed:latest
    secrets:
      clientId: ${{ secrets.AZURE_CLIENT_ID }}
      tenantId: ${{ secrets.AZURE_TENANT_ID }}
      subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      dockerUsername: ${{ secrets.DOCKER_USERNAME }}
      dockerPassword: ${{ secrets.DOCKER_PASSWORD }}
  deploy-home-app-to-prod:
    uses: './.github/workflows/deploy-infra-and-website-to-env.yml'
    needs: [deploy-news-feed-to-prod]
    with:
      dockerContext: './home-app'
      dockerFilePath: './home-app/Dockerfile'
      microFrontendService: 'home-app'
      environmentType: 'prod'
      resourceGroupName: intrinsic-rg
      dockerBaseUrl: index.docker.io
      dockerImageNameAndTag: module-federation-home-app:latest
    secrets:
      clientId: ${{ secrets.AZURE_CLIENT_ID }}
      tenantId: ${{ secrets.AZURE_TENANT_ID }}
      subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      dockerUsername: ${{ secrets.DOCKER_USERNAME }}
      dockerPassword: ${{ secrets.DOCKER_PASSWORD }}
