name: Deploy Azure Resources and Web Application to Environment

on:
  workflow_call:
    inputs:
      dockerContext:
        type: string
      dockerFilePath:
        type: string
      microFrontendService:
        type: string
      environmentType:
        type: string
      resourceGroupName:
        type: string
      dockerBaseUrl:
        type: string
      dockerImageNameAndTag:
        type: string
    secrets:
      dockerUsername:
        required: true
      dockerPassword:
        required: true
      clientId:
        required: true
      subscriptionId:
        required: true
      tenantId:
        required: true

permissions:
  id-token: write
  contents: write

jobs:
  deploy-infra:
    # environment:
    #   name: 'production'
    runs-on: ubuntu-latest
    outputs:
      webAppName: ${{ steps.deploy-infrastructure.outputs.webAppName }}
    steps:
    - name: Set up mutex
      uses: ben-z/gh-action-mutex@v1.0.0-alpha.10
    - uses: actions/checkout@v3
    - uses: azure/login@v2
      with:
        client-id: ${{ secrets.clientId }}
        tenant-id: ${{ secrets.tenantId }}
        subscription-id: ${{ secrets.subscriptionId }}
    - uses: azure/arm-deploy@v1
      id: deploy-infrastructure
      with:
        resourceGroupName: ${{ inputs.resourceGroupName }}
        template: ./deploy/main.bicep
        parameters: microFrontendService=${{ inputs.microFrontendService }} environmentType=${{ inputs.environmentType }} dockerImageFullUrl=${{ inputs.dockerBaseUrl }}/${{ secrets.dockerUsername }}/${{ inputs.dockerImageNameAndTag }}

  build:
    runs-on: 'ubuntu-latest'
    needs: deploy-infra

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.dockerUsername }}
        password: ${{ secrets.dockerPassword }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ inputs.dockerBaseUrl }}/${{ secrets.dockerUsername }}/${{ inputs.dockerImageNameAndTag }}
        file: ${{ inputs.dockerFilePath }}
        context: ${{ inputs.dockerContext }}

  deploy-app:
    runs-on: ubuntu-latest
    needs: [deploy-infra, build]
    # Outputs URL
    # environment:
    #   name: 'production'
    #   url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Set up mutex
      uses: ben-z/gh-action-mutex@v1.0.0-alpha.10
    - uses: azure/login@v2
      with:
        client-id: ${{ secrets.clientId }}
        tenant-id: ${{ secrets.tenantId }}
        subscription-id: ${{ secrets.subscriptionId }}
    
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ needs.deploy-infra.outputs.webAppName }}
        images: '${{ inputs.dockerBaseUrl }}/${{ secrets.dockerUsername }}/${{ inputs.dockerImageNameAndTag }}'
    
    - name: Set Docker Settings in Web App
      uses: azure/cli@v2
      with: 
        inlineScript: |
          az webapp config container set \
            --docker-registry-server-url 'https://${{ inputs.dockerBaseUrl }}' \
            --name ${{ needs.deploy-infra.outputs.webAppName }} \
            --resource-group ${{ inputs.resourceGroupName }}